services:

  postgres:
    image: postgres
    container_name: postgresDB
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"


  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: nest_api
    env_file: .env
    ports:
      - "${API_PORT2}:${API_PORT}"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL_CONTAINER}
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
